apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airbarium-api.fullname" . }}
  labels:
    {{- include "airbarium-api.labels" . | nindent 4 }}
data:
  {{- include "airbarium-api.configData" . | nindent 2 }}
